### PR TITLE
German Translation (removed BOM but still german index page not working)

### PR DESCRIPTION
**Pull request by sfkeller**
This PR consists another try of an initial german translation. I removed BOM marks at beginning of the Makdown text. Now it seems, that the german start page is still not recognized by github.io.

Pls. can somebody who knows the "learnosm logic" of multilanguage support, look at the helper files, so the start an other german pages show up? 

Once the german translation is established, it will be much easier to update it and to add other non-english pages.

P.S. Note that the german text hase been translated by interns and is still not fully spell checked.

### CODE REVIEW

**Comment by geomantic** [comment]
Hi Stefan, thanks for your patience. I'll look into the LearnOSM process to see if we can replicate their process.

**Comment by geomantic** [comment]
Just FYI, I just got this build warning, though I don't think it's related to the display of the German version:

"The page build completed successfully, but returned the following warning:
It looks like you're using GitHub Pages to distribute binary files. We strongly suggest that you use releases to ship projects on GitHub. Releases are GitHub's way of packaging and providing software to your users. You can think of it as a replacement to using downloads to provide software. We found the following file(s) which may be a good candidate for releases: files/USBDrivers_231.exe. For more information, see https://help.github.com/articles/about-releases/."

Not sure how this got into the repo, but I'm certain it's not needed.

**Comment by sfkeller** [comment]
USBDrivers_231.exe has nothing to do with Germa version. It seems, that it already existed here: https://github.com/hotosm/learnosm/tree/gh-pages/files . It's maybe a helper SW for this?
https://github.com/hotosm/learnosm/blob/gh-pages/files/OSMTracker_en.pdf

**Comment by sfkeller** [comment]
E.g. http://teachosm.org/de/workflow/ is working but the homepage http://teachosm.org/de/ gives 404. I fiddled around the config files on my fork but gave up after a while.

**Comment by geomantic** [comment]
You're absolutely correct. I just found that out independently. Thanks all the same. 

Okay, I'm comparing config files on LearnOSM and TeachOSM. I'll also reach out to @Nick-Tallguy who may have some insights. 

Special thanks for your persistence. We'd really like to get this going, too!

**Comment by Nick-Tallguy** [comment]
Steven,

Sorry, not ignoring this, but have been rushing in circles. Will try to 
look soon.


Regards


Nick

**Comment by Nick-Tallguy** [comment]
Hi,
I've carried out a little test and I think I can see your problem - you need to copy the 3 files;
* 0100-01-01-contribute.md,  
* 0100-01-01-index.md &  
* 0100-01-01-status.md
which are currently in /_posts/en and place the copies in /_posts/de  

Each of the files will also need translating - everywhere it mentions /en/ needs to read /de/  There is also lots of text - think it is everything between the speech marks from memory that will need translation as well.

I can place the files in the correct place for you, but they will be in English as my language skills are not that great.

I have tested this locally, and it works, so it shouldn't take long to fix.

Regards

Nick

**Comment by sfkeller** [comment]
Hi Nick,
Many thanks for debugging! Can't understand why we overlooked that. 
Yes, can you copy the 3 files to the correct place? I think I can organize the german translation within coming few weeks.

**Pull request merged**
